name: envaultko-dev

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/envaultko-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
    depends_on:
      - db
      - mailpit

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 7102:8080
    environment:
      ADMINER_DESIGN: pepa-linha

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 7103:8025
      - 7104:1025
    volumes:
      - mailpit:/data
    environment:
      MP_MAX_MESSAGES: 1000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db:
  mailpit:
